import './globals.css'
import { Inter } from 'next/font/google'
import Head from 'next/head'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Copy-Pasty',
  description: 'Generated by Montech',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Head>
        <link rel="icon" href="/favicon.ico" /> {/* Change the href value if your favicon file has a different name or extension */}
      </Head>
      <body className={inter.className}>{children}</body>
    </html>
  )
}
